baseURL = 'https://kocoler.github.io'
languageCode = 'en-us'
title = "kocoler's blog"
author = "kocoler"
theme = "papermod"
disqusShortname = "kocoler's blog"

[params]
showtoc = true
tocopen = false
ShowCodeCopyButtons = true
hideSummary = false

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "I'm a junior of CCNU, loving Go and focus on cloud native and public classes."

[[params.socialIcons]]
name = "github"
url  = "https://github.com/kocoler"

[[params.socialIcons]]
name = "email"
url = "mailto:tsglsdrs@163.com"


